version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: smartbrain-postgres
    environment:
      - POSTGRES_DB=smartbrain_db
      - POSTGRES_PASSWORD=lasBr01
      - POSTGRES_USER=postgres
    networks:
      - REDESMARTBRAIN
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: smartbrain-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - REDESMARTBRAIN
    ports:
      - "5050:80"
    depends_on:
      - postgres

networks:
  REDESMARTBRAIN:
    driver: bridge

volumes:
  postgres_data:
